---
- name: Configure Bastion Host
  hosts: bastion
  become: yes
  tasks:
    - name: Install Apache and PHP
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
        update_cache: yes

    - name: Install MySQL client core 8.0
      apt:
        name: mysql-client-core-8.0
        state: present

    - name: Remove index.php from /var/www/html
      file:
        path: /var/www/html/index.php
        state: absent

    - name: Ensure /var/www/html is empty before cloning repository
      file:
        path: /var/www/html/*
        state: absent
      ignore_errors: yes  # Ignore errors if the directory is already empty

    - name: Clone my_website repository
      git:
        repo: 'https://github.com/Ramratan100/my_website.git'
        dest: /var/www/html/
        clone: yes
        update: yes
        version: main  # Specify the branch if you want a specific one (optional)
        force: yes  # This ensures that the latest version of the repository is pulled

    - name: Copy tokyojenkins.pem to /home/ubuntu
      copy:
        src: /var/lib/jenkins/tokyojenkins.pem
        dest: /home/ubuntu/tokyojenkins.pem
        owner: ubuntu
        group: ubuntu
        mode: '0400'

    - name: Update Apache DirectoryIndex to prioritize index.php
      lineinfile:
        path: /etc/apache2/mods-enabled/dir.conf
        regexp: '^#?DirectoryIndex'
        line: 'DirectoryIndex index.php index.html index.pl index.cgi index.xhtml index.htm'
        state: present
        backrefs: yes  # Ensure the changes are applied directly to the correct line

    - name: Restart Apache to apply changes
      systemd:
        name: apache2
        state: restarted
        enabled: yes
