---
- name: Configure Bastion Host
  hosts: bastion
  become: yes
  tasks:
    - name: Install Apache and PHP
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
        update_cache: yes

    - name: Remove index.php from /var/www/html
      file:
        path: /var/www/html/index.php
        state: absent

    - name: Clone my_website repository
      git:
        repo: 'https://github.com/Ramratan100/my_website.git'
        dest: /var/www/html/
        clone: yes
        update: yes
        version: main  # Specify the branch if you want a specific one (optional)
        force: yes  # This ensures that the latest version of the repository is pulled

    - name: Copy tokyojenkins.pem to /home/ubuntu
      copy:
        src: /var/lib/jenkins/tokyojenkins.pem
        dest: /home/ubuntu/tokyojenkins.pem
        owner: ubuntu
        group: ubuntu
        mode: '0400'
