---
- name: Configure Bastion Host
  hosts: bastion
  become: yes
  tasks:
    - name: Install Apache and PHP
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
        update_cache: yes

    - name: Ensure /var/www/html is empty
      file:
        path: /var/www/html/*
        state: absent
      ignore_errors: yes  # Ignore errors if the directory is empty

    - name: Clone my_website repository
      git:
        repo: 'https://github.com/Ramratan100/my_website.git'
        dest: /var/www/html/
        clone: yes
        update: yes
        version: main  # Specify the branch if you want a specific one (optional)
        force: yes  # This ensures that the latest version of the repository is pulled
